### ISSUE TITLE
Possible corrupt output files

### ISSUE THREAD

**Issue by phidahl** [DC-analysis/DCKit#28]
Files written by DCKit 0.14.4 (from pip) on a Windows 11 PC cannot be properly read with HDFView. I tried HDFView 3.1.0 and 3.2.0 on Windows and Mac computers.

The dataset index seems to be ok. But if I click a table HDFView shows an error "Failed to read scalar dataset: Can't open directory or file" and "*** Error: unable to load table data ***"

I also tried renaming the file (to avoid fancy characters).

Opening the file in ShapeOut, however, worked normally.

Since I consider HDFView as reference for sane hdf5 file, I think we should investigate what the problem might be. My first research was going into the direction of compression.

**Comment by paulmueller** [comment]
This is because we now use zstd for (faster and better) compression.

Please take a look here for a system-wide fix: https://github.com/DC-analysis/dclab/issues/177
